language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p build/logs
  - chmod -Rf tests/runtime
  - pwd
  - ls

script:
 - php vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests

after_script:
 - php vendor/bin/coveralls -v

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'