language: php

php:
  - '7.1'
  - '7.2'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p build/logs
  - chmod -Rf 0777 tests/runtime
  - pwd
  - ls

script:
 - php vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests